baseURL: https://chalisehari.com.np/
languageCode: en-us
build:
  writeStats: true
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS

security:
  exec:
    allow:
      - '^(dart-)?sass$'
      - '^go$'
      - '^git$'
      - '^node$'
      - '^postcss$'
      - '^tailwindcss$'
  http:
    methods:
      - (?i)GET
    urls:
      - '.*'
title: Hari Chalise
theme: aafu

params:
  author: Hari Chalise
  description: Linux enthusiast from Kathmandu, Nepal
  copyright: "© 2025 Hari Chalise"
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: true
  accordion:
    - item: about_me
      expand: true
    - item: experiences
    - item: education
    - item: projects
      panel_id: projects-panel
    - item: tech_stack
    - item: skills
      panel_id: skill-panel
    - item: currently
    - item: hobbies
    - item: uses
